#!/bin/bash
echo "========= Betty Linter ========="
betty ./$1.c

echo "============== GCC ============="

gcc -Wall -pedantic -Werror -Wextra -std=gnu89 _putchar.c 0-strcat.c 1-strncat.c 2-strncpy.c 3-strcmp.c 4-rev_array.c 5-string_toupper.c 6-cap_string.c 7-leet.c "${1:0:1}"-main.c -o "${1:0:1}"-main

echo "============ Run Code ==========="
./"${1:0:1}"-main