#!/bin/bash
echo "========= Betty Linter ========="
betty ./$1.c

echo "============== GCC ============="

gcc -Wall -pedantic -Werror -Wextra -std=gnu89 _putchar.c 0-reset_to_98.c 1-swap.c 2-strlen.c 3-puts.c 4-print_rev.c 5-rev_string.c  6-puts2.c 7-puts_half.c 8-print_array.c 9-strcpy.c "${1:0:1}"-main.c -o "${1:0:1}"-main

# echo "============ Run Code ==========="
# ./$